name: FPD17
channels:
  - statiskit
  - r
dependencies:
  - python=2.7
  - r-essentials
  - r-mglm
  - r-bivpois
  - rpy2
  - pandas
  - matplotlib
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - python-statiskit_linalg
  - python-statiskit_core
  - python-statiskit_glm
