{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bivpois
  version: 0.50.2

source:
  fn: bivpois_0.50-2.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/Archive/bivpois/bivpois_0.50-2.tar.gz

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - libtoolchain
  run:
    - r-base

test:
  commands:
    - $R -e "library('bivpois')"           # [not win]
    - "\"%R%\" -e \"library('bivpois')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=bivpois
  license: GPL (>= 2)
  summary: 'Functions for fitting Bivariate Poisson Models using the EM algorithm. Details can be found in Karlis and Ntzoufras (2003, RSS D & 2004,AUEB Technical Report)'

  license_family: GPL3
