package:
  name: r-iterators
  version: "1.0.8"

source:
  fn: iterators_1.0.8.tar.gz
  url: https://cran.r-project.org/src/contrib/iterators_1.0.8.tar.gz
  sha256: ae4ea23385776eb0c06c992a3da6b0256a6c84558c1061034c5a1fbdd43d05b8

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('iterators')"           # [not win]
    - "\"%R%\" -e \"library('iterators')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=iterators
  license: Apache License 2.0
  summary: Support for iterators, which allow a programmer to traverse through all the elements
    of a vector, list, or other collection of data.