package:
  name: r-doparallel
  version: "1.0.11"

source:
  fn: doParallel_1.0.11.tar.gz
  url: https://cran.r-project.org/src/contrib/doParallel_1.0.11.tar.gz
  sha256: 4ccbd2eb46d3e4f5251b0c3de4d93d9168b02bb0be493656d6aea236667ff76a

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-foreach
    - r-iterators
  run:
    - r-base
    - r-foreach
    - r-iterators

test:
  commands:
    - $R -e "library('doParallel')"           # [not win]
    - "\"%R%\" -e \"library('doParallel')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=doParallel
  license: GPL-2
  summary: Provides a parallel backend for the %dopar% function using the parallel package.